# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"study_tags": "00_core.ipynb",
         "Path.dcmread": "00_core.ipynb",
         "DcmDataset.as_dict": "00_core.ipynb",
         "pd.DataFrame.from_dicoms": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://wfwiggins.github.io/dicomtools/"

git_url = "https://github.com/wfwiggins/dicomtools/tree/master/"

def custom_doc_links(name): return None
